spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresDb
    username: admin
    password: admin
  liquibase:
    change-log: db/changelog.json
    drop-first: true